<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### Leand

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```

```{r}
Dataset <-
readXL("D:/Faculdade/4 - Período/Estatistica_Basica/Trabalho01/Exercicio01/Dados_Renda_Trabalho01.xlsx",
  
rownames=FALSE, header=TRUE, na="", sheet="Dados_Trabalho_01",
stringsAsFactors=TRUE)
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
dados<-Dataset$renda
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
situacao<-Dataset$Situacao_Laboral
```


```{r}
n<-150
```


```{r}
summary(situacao)
```


```{r}
sit1<-c()
```


```{r}
sit2<-c()
```


```{r}
sit3<-c()
```


```{r}
sit4<-c()
```


```{r}
sit5<-c()
```


```{r}
sit6<-c()
```


```{r}
sit7<-c()
```


```{r}
i1<-1
```


```{r}
i2<-1
```


```{r}
i3<-1
```


```{r}
i4<-1
```


```{r}
i5<-1
```


```{r}
i6<-1
```


```{r}
i7<-1
```


```{r}
for(i in 1:N){
if(situacao[i]=="1"){
sit1[i1]<-dados[i]
i1<-i1+1
}
else{
if(situacao[i]=="2"){
sit2[i2]<-dados[i]
i2<-i2+1
}
else{
if(situacao[i]=="3"){
sit3[i3]<-dados[i]
i3<-i3+1
}
else{
if(situacao[i]=="4"){
sit4[i4]<-dados[i]
i4<-i4+1
}
else{
if(situacao[i]=="5"){
sit5[i5]<-dados[i]
i5<-i5+1
}
else{
if(situacao[i]=="6"){
sit6[i6]<-dados[i]
i6<-i6+1
}
else{
sit7[i7]<-dados[i]
i7<-i7+1
}
}
}
}
}
}
}
```


```{r}
sit1
```


```{r}
sit2
```


```{r}
sit3
```


```{r}
sit4
```


```{r}
sit5
```


```{r}
sit6
```


```{r}
sit7
```


```{r}
f<-n/N
```


```{r}
f
```


```{r}
n1<-f*(length(sit1))
```


```{r}
n1
```


```{r}
n2<-f*(length(sit2))
```


```{r}
n2
```


```{r}
n3<-f*(length(sit3))
```


```{r}
n3
```


```{r}
n4<-f*(length(sit4))
```


```{r}
n4
```


```{r}
n5<-f*(length(sit5))
```


```{r}
n5
```


```{r}
n6<-f*(length(sit6))
```


```{r}
n6
```


```{r}
n7<-f*(length(sit7))
```


```{r}
n7
```


```{r}
amostra1<-sample(sit1,n1)
```


```{r}
amostra2<-sample(sit2,n2)
```


```{r}
amostra3<-sample(sit3,n3)
```


```{r}
amostra4<-sample(sit4,n4)
```


```{r}
amostra5<-sample(sit5,n5)
```


```{r}
amostra6<-sample(sit6,n6)
```


```{r}
amostra7<-sample(sit7,n7)
```


```{r}
amostraEst<-c(amostra1,amostra2,amostra3,amostra4,amostra5,amostra6,
  amostra7)
```


```{r}
amostraEst
```


```{r}
mediaSal<-(mean(amostraEst))/12
```


```{r}
mediaSal
```


```{r}
Dataset <-
readXL("D:/Faculdade/4 - Período/Estatistica_Basica/Trabalho01/Exercicio01/Dados_Renda_Trabalho01.xlsx",
  
rownames=FALSE, header=TRUE, na="", sheet="Dados_Trabalho_01",
stringsAsFactors=TRUE)
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
dados<-Dataset$renda
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
situacao<-Dataset$Situacao_Laboral
```


```{r}
n<-150
```


```{r}
summary(situacao)
```


```{r}
sit1<-c()
```


```{r}
sit2<-c()
```


```{r}
sit3<-c()
```


```{r}
sit4<-c()
```


```{r}
sit5<-c()
```


```{r}
sit6<-c()
```


```{r}
sit7<-c()
```


```{r}
i1<-1
```


```{r}
i2<-1
```


```{r}
i3<-1
```


```{r}
i4<-1
```


```{r}
i5<-1
```


```{r}
i6<-1
```


```{r}
i7<-1
```


```{r}
for(i in 1:N){
if(situacao[i]=="1"){
sit1[i1]<-dados[i]
i1<-i1+1
}
else{
if(situacao[i]=="2"){
sit2[i2]<-dados[i]
i2<-i2+1
}
else{
if(situacao[i]=="3"){
sit3[i3]<-dados[i]
i3<-i3+1
}
else{
if(situacao[i]=="4"){
sit4[i4]<-dados[i]
i4<-i4+1
}
else{
if(situacao[i]=="5"){
sit5[i5]<-dados[i]
i5<-i5+1
}
else{
if(situacao[i]=="6"){
sit6[i6]<-dados[i]
i6<-i6+1
}
else{
sit7[i7]<-dados[i]
i7<-i7+1
}
}
}
}
}
}
}
```


```{r}
sit1
```


```{r}
sit2
```


```{r}
sit3
```


```{r}
sit4
```


```{r}
sit5
```


```{r}
sit6
```


```{r}
sit7
```


```{r}
f<-n/N
```


```{r}
f
```


```{r}
n1<-round(f*(length(sit1)),0)
```


```{r}
n1
```


```{r}
n2<-round(f*(length(sit2)),0)
```


```{r}
n2
```


```{r}
n3<-round(f*(length(sit3)),0)
```


```{r}
n3
```


```{r}
n4<-round(f*(length(sit4)),0)
```


```{r}
n4
```


```{r}
n5<-round(f*(length(sit5)),0)
```


```{r}
n5
```


```{r}
n6<-round(f*(length(sit6)),0)
```


```{r}
n6
```


```{r}
n7<-round(f*(length(sit7)),0)
```


```{r}
n7
```


```{r}
n1+n2+n3+n4+n5+n6+n7
```


```{r}
amostra1<-sample(sit1,n1)
```


```{r}
amostra2<-sample(sit2,n2)
```


```{r}
amostra3<-sample(sit3,n3)
```


```{r}
amostra4<-sample(sit4,n4)
```


```{r}
amostra5<-sample(sit5,n5)
```


```{r}
amostra6<-sample(sit6,n6)
```


```{r}
amostra7<-sample(sit7,n7)
```


```{r}
amostraEst<-c(amostra1,amostra2,amostra3,amostra4,amostra5,amostra6,
  amostra7)
```


```{r}
amostraEst
```


```{r}
mediaSal<-(mean(amostraEst))/12
```


```{r}
mediaSal
```


```{r}
n1<-round(f*(length(sit1)),0)
```


```{r}
n1
```


```{r}
m1<-round(((length(sit1))/N)*n,0)
```


```{r}
m1
```


```{r}
n7<-round(f*(length(sit7)),0)
```


```{r}
n7
```


```{r}
m7<-round(((length(sit7))/N)*n,0)
```


```{r}
m7
```


```{r}
Dataset <-
readXL("D:/Faculdade/4 - Período/Estatistica_Basica/Trabalho01/Exercicio01/Dados_Renda_Trabalho01.xlsx",
  
rownames=FALSE, header=TRUE, na="", sheet="Dados_Trabalho_01",
stringsAsFactors=TRUE)
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
dados<-Dataset$Identificador
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
sit1
```


```{r}
Dataset <-
readXL("D:/Faculdade/4 - Período/Estatistica_Basica/Trabalho01/Exercicio01/Dados_Renda_Trabalho01.xlsx",
  
rownames=FALSE, header=TRUE, na="", sheet="Dados_Trabalho_01",
stringsAsFactors=TRUE)
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
dados<-Dataset$Identificador
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
situacao<-Dataset$Situacao_Laboral
```


```{r}
n<-150
```


```{r}
summary(situacao)
```


```{r}
sit1<-c()
```


```{r}
sit2<-c()
```


```{r}
sit3<-c()
```


```{r}
sit4<-c()
```


```{r}
sit5<-c()
```


```{r}
sit6<-c()
```


```{r}
sit7<-c()
```


```{r}
i1<-1
```


```{r}
i2<-1
```


```{r}
i3<-1
```


```{r}
i4<-1
```


```{r}
i5<-1
```


```{r}
i6<-1
```


```{r}
i7<-1
```


```{r}
for(i in 1:N){
if(situacao[i]=="1"){
sit1[i1]<-dados[i]
i1<-i1+1
}
else{
if(situacao[i]=="2"){
sit2[i2]<-dados[i]
i2<-i2+1
}
else{
if(situacao[i]=="3"){
sit3[i3]<-dados[i]
i3<-i3+1
}
else{
if(situacao[i]=="4"){
sit4[i4]<-dados[i]
i4<-i4+1
}
else{
if(situacao[i]=="5"){
sit5[i5]<-dados[i]
i5<-i5+1
}
else{
if(situacao[i]=="6"){
sit6[i6]<-dados[i]
i6<-i6+1
}
else{
sit7[i7]<-dados[i]
i7<-i7+1
}
}
}
}
}
}
}
```


```{r}
sit1
```


```{r}
Dataset <-
readXL("D:/Faculdade/4 - Período/Estatistica_Basica/Trabalho01/Exercicio01/Dados_Renda_Trabalho01.xlsx",
  
rownames=FALSE, header=TRUE, na="", sheet="Dados_Trabalho_01",
stringsAsFactors=TRUE)
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
dados<-Dataset$Identificador
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
situacao<-Dataset$Situacao_Laboral
```


```{r}
n<-150
```


```{r}
summary(situacao)
```


```{r}
sit1<-c()
```


```{r}
sit2<-c()
```


```{r}
sit3<-c()
```


```{r}
sit4<-c()
```


```{r}
sit5<-c()
```


```{r}
sit6<-c()
```


```{r}
sit7<-c()
```


```{r}
i1<-1
```


```{r}
i2<-1
```


```{r}
i3<-1
```


```{r}
i4<-1
```


```{r}
i5<-1
```


```{r}
i6<-1
```


```{r}
i7<-1
```


```{r}
for(i in 1:N){
if(situacao[i]=="1"){
sit1[i1]<-dados[i]
i1<-i1+1
}
else{
if(situacao[i]=="2"){
sit2[i2]<-dados[i]
i2<-i2+1
}
else{
if(situacao[i]=="3"){
sit3[i3]<-dados[i]
i3<-i3+1
}
else{
if(situacao[i]=="4"){
sit4[i4]<-dados[i]
i4<-i4+1
}
else{
if(situacao[i]=="5"){
sit5[i5]<-dados[i]
i5<-i5+1
}
else{
if(situacao[i]=="6"){
sit6[i6]<-dados[i]
i6<-i6+1
}
else{
sit7[i7]<-dados[i]
i7<-i7+1
}
}
}
}
}
}
}
```


```{r}
sit1
```


```{r}
sit2
```


```{r}
sit3
```


```{r}
sit4
```


```{r}
sit5
```


```{r}
sit6
```


```{r}
sit7
```


```{r}
f<-n/N
```


```{r}
f
```


```{r}
n1<-round(f*(length(sit1)),0)
```


```{r}
n1
```


```{r}
n2<-round(f*(length(sit2)),0)
```


```{r}
n2
```


```{r}
n3<-round(f*(length(sit3)),0)
```


```{r}
n3
```


```{r}
n4<-round(f*(length(sit4)),0)
```


```{r}
n4
```


```{r}
n5<-round(f*(length(sit5)),0)
```


```{r}
n5
```


```{r}
n6<-round(f*(length(sit6)),0)
```


```{r}
n6
```


```{r}
n7<-round(f*(length(sit7)),0)
```


```{r}
n7
```


```{r}
amostra1<-sample(sit1,n1)
```


```{r}
amostra2<-sample(sit2,n2)
```


```{r}
amostra3<-sample(sit3,n3)
```


```{r}
amostra4<-sample(sit4,n4)
```


```{r}
amostra5<-sample(sit5,n5)
```


```{r}
amostra6<-sample(sit6,n6)
```


```{r}
amostra7<-sample(sit7,n7)
```


```{r}
amostraEst<-c(amostra1,amostra2,amostra3,amostra4,amostra5,amostra6,
  amostra7)
```


```{r}
amostraEst
```


```{r}
renda<-Dataset$renda
```


```{r}
renda<-Dataset$renda
```


```{r}
mediaSal<-(mean(amostraEst))/12
```


```{r}
mediaSal
```


```{r}
valorTeste<-renda[73169]
```


```{r}
valorTeste
```


```{r}
Dataset <-
readXL("D:/Faculdade/4 - Período/Estatistica_Basica/Trabalho01/Exercicio01/Dados_Renda_Trabalho01.xlsx",
  
rownames=FALSE, header=TRUE, na="", 
  sheet="Dados_Trabalho_01",
stringsAsFactors=TRUE)
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
dados<-Dataset$Identificador
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
situacao<-Dataset$Situacao_Laboral
```


```{r}
n<-150
```


```{r}
summary(situacao)
```


```{r}
sit1<-c()
```


```{r}
sit2<-c()
```


```{r}
sit3<-c()
```


```{r}
sit4<-c()
```


```{r}
sit5<-c()
```


```{r}
sit6<-c()
```


```{r}
sit7<-c()
```


```{r}
i1<-1
```


```{r}
i2<-1
```


```{r}
i3<-1
```


```{r}
i4<-1
```


```{r}
i5<-1
```


```{r}
i6<-1
```


```{r}
i7<-1
```


```{r}
for(i in 1:N){
if(situacao[i]=="1"){
sit1[i1]<-dados[i]
i1<-i1+1
}
else{
if(situacao[i]=="2"){
sit2[i2]<-dados[i]
i2<-i2+1
}
else{
if(situacao[i]=="3"){
sit3[i3]<-dados[i]
i3<-i3+1
}
else{
if(situacao[i]=="4"){
sit4[i4]<-dados[i]
i4<-i4+1
}
else{
if(situacao[i]=="5"){
sit5[i5]<-dados[i]
i5<-i5+1
}
else{
if(situacao[i]=="6"){
sit6[i6]<-dados[i]
i6<-i6+1
}
else{
sit7[i7]<-dados[i]
i7<-i7+1
}
}
}
}
}
}
}
```


```{r}
sit1
```


```{r}
sit2
```


```{r}
sit3
```


```{r}
sit4
```


```{r}
sit5
```


```{r}
sit6
```


```{r}
sit7
```


```{r}
f<-n/N
```


```{r}
f
```


```{r}
n1<-round(f*(length(sit1)),0)
```


```{r}
n1
```


```{r}
n2<-round(f*(length(sit2)),0)
```


```{r}
n2
```


```{r}
n3<-round(f*(length(sit3)),0)
```


```{r}
n3
```


```{r}
n4<-round(f*(length(sit4)),0)
```


```{r}
n4
```


```{r}
n5<-round(f*(length(sit5)),0)
```


```{r}
n5
```


```{r}
n6<-round(f*(length(sit6)),0)
```


```{r}
n6
```


```{r}
n7<-round(f*(length(sit7)),0)
```


```{r}
n7
```


```{r}
amostra1<-sample(sit1,n1)
```


```{r}
amostra2<-sample(sit2,n2)
```


```{r}
amostra3<-sample(sit3,n3)
```


```{r}
amostra4<-sample(sit4,n4)
```


```{r}
amostra5<-sample(sit5,n5)
```


```{r}
amostra6<-sample(sit6,n6)
```


```{r}
amostra7<-sample(sit7,n7)
```


```{r}
amostraEst<-c(amostra1,amostra2,amostra3,amostra4,
  amostra5,amostra6,amostra7)
```


```{r}
amostraEst
```


```{r}
renda<-Dataset$renda
```


```{r}
rendasAmostrais<-c()
```


```{r}
for(i in 1:length(amostraEst)){
rendasAmostrais[i]<-renda[amostraEst[i]]
}
```


```{r}
rendasAmostrais
```


```{r}
mediaSal<-(mean(rendasAmostrais))/12
```


```{r}
mediaSal
```


```{r}
Dataset <-
readXL("D:/Faculdade/4 - Período/Estatistica_Basica/Trabalho01/Exercicio01/Dados_Renda_Trabalho01.xlsx",
  
rownames=FALSE, header=TRUE, na="", 
  sheet="Dados_Trabalho_01",
stringsAsFactors=TRUE)
```


```{r}
Dataset <- within(Dataset, {
Situacao_Laboral <- as.factor(Situacao_Laboral)
})
```


```{r}
dados<-Dataset$Identificador
```


```{r}
N<-length(dados)
```


```{r}
N
```


```{r}
situacao<-Dataset$Situacao_Laboral
```


```{r}
n<-150
```


```{r}
summary(situacao)
```


```{r}
sit1<-c()
```


```{r}
sit2<-c()
```


```{r}
sit3<-c()
```


```{r}
sit4<-c()
```


```{r}
sit5<-c()
```


```{r}
sit6<-c()
```


```{r}
sit7<-c()
```


```{r}
i1<-1
```


```{r}
i2<-1
```


```{r}
i3<-1
```


```{r}
i4<-1
```


```{r}
i5<-1
```


```{r}
i6<-1
```


```{r}
i7<-1
```


```{r}
for(i in 1:N){
if(situacao[i]=="1"){
sit1[i1]<-dados[i]
i1<-i1+1
}
else{
if(situacao[i]=="2"){
sit2[i2]<-dados[i]
i2<-i2+1
}
else{
if(situacao[i]=="3"){
sit3[i3]<-dados[i]
i3<-i3+1
}
else{
if(situacao[i]=="4"){
sit4[i4]<-dados[i]
i4<-i4+1
}
else{
if(situacao[i]=="5"){
sit5[i5]<-dados[i]
i5<-i5+1
}
else{
if(situacao[i]=="6"){
sit6[i6]<-dados[i]
i6<-i6+1
}
else{
sit7[i7]<-dados[i]
i7<-i7+1
}
}
}
}
}
}
}
```


```{r}
sit1
```


```{r}
sit2
```


```{r}
sit3
```


```{r}
sit4
```


```{r}
sit5
```


```{r}
sit6
```


```{r}
sit7
```


```{r}
f<-n/N
```


```{r}
f
```


```{r}
n1<-round(f*(length(sit1)),0)
```


```{r}
n1
```


```{r}
n2<-round(f*(length(sit2)),0)
```


```{r}
n2
```


```{r}
n3<-round(f*(length(sit3)),0)
```


```{r}
n3
```


```{r}
n4<-round(f*(length(sit4)),0)
```


```{r}
n4
```


```{r}
n5<-round(f*(length(sit5)),0)
```


```{r}
n5
```


```{r}
n6<-round(f*(length(sit6)),0)
```


```{r}
n6
```


```{r}
n7<-round(f*(length(sit7)),0)
```


```{r}
n7
```


```{r}
amostra1<-sample(sit1,n1)
```


```{r}
amostra2<-sample(sit2,n2)
```


```{r}
amostra3<-sample(sit3,n3)
```


```{r}
amostra4<-sample(sit4,n4)
```


```{r}
amostra5<-sample(sit5,n5)
```


```{r}
amostra6<-sample(sit6,n6)
```


```{r}
amostra7<-sample(sit7,n7)
```


```{r}
amostraEst<-c(amostra1,amostra2,amostra3,amostra4,
  amostra5,amostra6,amostra7)
```


```{r}
amostraEst
```


```{r}
renda<-Dataset$renda
```


```{r}
rendasAmostrais<-c()
```


```{r}
for(i in 1:length(amostraEst)){
rendasAmostrais[i]<-renda[amostraEst[i]]
}
```


```{r}
rendasAmostrais
```


```{r}
mediaSal<-(mean(rendasAmostrais))/12
```


```{r}
mediaSal
```


```{r}
rendaMedia<-mean(rendasAmostrais)
```


```{r}
rendaMedia
```


```{r}
mediaSal<-rendaMedia/12
```


```{r}
mediaSal
```


```{r}
rendaMedia<-mean(rendasAmostrais)
```


```{r}
rendaMedia
```


```{r}
mediaSal<-rendaMedia/12
```


```{r}
mediaSal
```


